### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by bublikOff** [Limych/ha-beward#16]
В последнее время замучала ошибка про ffmpeg ... один раз стартует нормально а другой орет. Т.е. удачный старт происходит ровно через раз
`
2021-09-24 20:24:31 ERROR (MainThread) [homeassistant.setup] Error during setup of component ffmpeg
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 255, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/ffmpeg/__init__.py", line 63, in async_setup
    await manager.async_get_version()
  File "/usr/src/homeassistant/homeassistant/components/ffmpeg/__init__.py", line 138, in async_get_version
    ffversion = FFVersion(self._bin)
TypeError: __init__() missing 1 required positional argument: 'loop'
2021-09-24 20:24:31 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of beward. Setup failed for dependencies: ffmpeg
2021-09-24 20:24:31 ERROR (MainThread) [homeassistant.setup] Setup failed for beward: Could not set up all dependencies.
`

**Comment by bublikOff** [comment]
Так и не получил к сожалению варианта решить ...
как показывало что ошибка зависимости так и показывает ...
при этом ffmpeg присутствует в докере ... при этом рестарт сервера решает проблему до следующего рестарта ...
появляется через раз

**Comment by Limych** [comment]
Во-первых, я даже не читаю багрепорты, оформленные не по шаблону. Ибо если человек считает, что ему лень облегчить мне понимание ситуации, то я сразу вспоминаю, что ему ничего не должен.

Во-вторых, продукт поставляется AS IS. Да, в нём могут быть ошибки. Но специально их искать и исправлять я не буду до тех пор, пока не буду за это получать зарплату. А покуда это не так, всё делается по остаточному принципу.

Если Вы знаете, как исправить эту ошибку, Вы вольны прислать PR. Я его проверю и добавлю в репозиторий. И будет Вам «респект и уважуха». В противном же случае, либо Вы ждёте, когда всё «само исправится», либо оплачиваете мне рабочее время по исправлению этой ошибки.

Ничего личного.

**Comment by bublikOff** [comment]
гениальный ответ ... а главное решает проблему на все 100
