### ISSUE TITLE
Error while setting up beward platform for camera

### ISSUE THREAD

**Issue by wqrwefdgfv** [Limych/ha-beward#78]
### System Health details

Beward Integration 1.1.29
Core 2024.11.0
Supervisor 2024.11.2
Operating System 13.2
Пользовательский интерфейс 20241106.0

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-blueprint/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Регистратор: homeassistant.components.camera
Источник: helpers/entity_platform.py:365
интеграция: Камера (документация, проблемы)
Первое сообщение: 09:20:37 (1 сообщений)
Последнее сообщение: 09:20:37

Error while setting up beward platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/beward/camera.py", line 80, in async_setup_entry
    entities.extend(await _async_setup_entities(controller, config))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/beward/camera.py", line 107, in _async_setup_entities
    entities.append(BewardFileCamera(controller, camera_type))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/beward/camera.py", line 211, in __init__
    super().__init__(
TypeError: LocalFile.__init__() missing 1 required positional argument: 'unique_id'

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
2024-11-08 09:20:37.129 INFO (MainThread) [homeassistant.components.camera] Setting up beward.camera
2024-11-08 09:20:37.129 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up beward.binary_sensor
2024-11-08 09:20:37.129 DEBUG (MainThread) [custom_components.beward.binary_sensor] Beward 64396 Ding binary sensor state changed to "False"
2024-11-08 09:20:37.129 DEBUG (MainThread) [custom_components.beward.binary_sensor] Beward 64396 Motion binary sensor state changed to "False"
2024-11-08 09:20:37.129 DEBUG (MainThread) [custom_components.beward.binary_sensor] Beward 64396 Online binary sensor state changed to "True"
2024-11-08 09:20:37.129 INFO (MainThread) [homeassistant.components.sensor] Setting up beward.sensor
2024-11-08 09:20:37.129 DEBUG (MainThread) [custom_components.beward.sensor] {'840e7cdf2e35394cc320d8e15a3081a8': {'undo_update_listener': <function ConfigEntry.add_update_listener.<locals>.<lambda> at 0x7fc180b734c0>, 0: <custom_components.beward.BewardController object at 0x7fc17f658c20>}}
2024-11-08 09:20:37.133 INFO (MainThread) [homeassistant.setup] Setting up media_player
2024-11-08 09:20:37.135 INFO (MainThread) [homeassistant.setup] Setup of domain media_player took 0.00 seconds
2024-11-08 09:20:37.135 INFO (MainThread) [homeassistant.setup] Setting up select
2024-11-08 09:20:37.135 INFO (MainThread) [homeassistant.setup] Setup of domain select took 0.00 seconds
2024-11-08 09:20:37.136 INFO (MainThread) [homeassistant.components.camera] Setting up yandex_station.camera
2024-11-08 09:20:37.139 INFO (MainThread) [homeassistant.components.conversation] Setting up yandex_station.conversation
2024-11-08 09:20:37.145 INFO (MainThread) [homeassistant.components.media_player] Setting up yandex_station.media_player
2024-11-08 09:20:37.154 INFO (MainThread) [homeassistant.components.select] Setting up yandex_station.select
2024-11-08 09:20:37.154 ERROR (MainThread) [homeassistant.components.camera] Error while setting up beward platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/beward/camera.py", line 80, in async_setup_entry
    entities.extend(await _async_setup_entities(controller, config))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/beward/camera.py", line 107, in _async_setup_entities
    entities.append(BewardFileCamera(controller, camera_type))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/beward/camera.py", line 211, in __init__
    super().__init__(
TypeError: LocalFile.__init__() missing 1 required positional argument: 'unique_id'
```

**Comment by wayfarer70** [comment]
У меня аналогичная ошибка.

**Comment by Vugl78** [comment]
Это поле видимо теперь обязательное.
