### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sergbmw** [Limych/ha-beward#8]
Уровень: ERROR
Logger: homeassistant.bootstrap
Source: util/package.py:51
First occurred: 15:23:09 (1 occurrences)
Last logged: 15:23:09

Error setting up integration beward - received exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 13), (line:1, col:14)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 47, in is_installed
    req = pkg_resources.Requirement.parse(package)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3164, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3109, in parse_requirements
    yield Requirement(line)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3119, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 100, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'eta'": Expected stringEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 64, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 158, in _async_setup_component
    await async_process_deps_reqs(hass, config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 75, in async_get_integration_with_requirements
    await async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 122, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 51, in is_installed
    req = pkg_resources.Requirement.parse(urlparse(package).fragment)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3164, in parse
    req, = parse_requirements(s)
ValueError: not enough values to unpack (expected 1, got 0)
Home Assistant работает!

**Comment by Limych** [comment]
Шаблоны были придуманы для того, чтобы всем облегчить жизнь.
Пожалуйста, заполните багрепорт в соответствии с шаблоном, который Вы проигнорировали. Вот он для справки: https://raw.githubusercontent.com/Limych/ha-beward/master/.github/ISSUE_TEMPLATE/bug_report.md

Если этого не случится в разумный срок, этот багрепорт будет закрыт.
