### ISSUE TITLE
Error after update HA to 2024.12

### ISSUE THREAD

**Issue by booroondook-eng** [Limych/ha-beward#81]
## System Information

version | core-2024.12.0
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.1.0-27-amd64
arch | x86_64
timezone | Europe/Moscow
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.1
Stage | running
Available Repositories | 1551
Downloaded Repositories | 85

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 12 (bookworm)
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.4.1
docker_version | 27.3.1
disk_total | 71.2 GB
disk_used | 25.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
supervisor_api | ok
version_api | ok
installed_addons | TasmoAdmin (0.31.0), ESPHome Device Compiler (2024.11.2), RHVoice (1.0.3), Matter Server (6.6.1), File editor (5.8.0), Whisper (2.3.0), Piper (1.5.2), openWakeWord (1.10.0), Assist Microphone (1.2.0), Zigbee2MQTT (1.42.0-2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 53
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20 ноября 2024 г. в 09:45
-- | --
current_recorder_run | 5 декабря 2024 г. в 10:53
estimated_db_size | 6243.11 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 0 / 13
local_online | 8 / 8

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 1.0.1
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-blueprint/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Log:
2024-12-05 10:54:13.589 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'beward': Requirements for beward not found: ['ha-av>=9.2'].

### Reproduction steps

1. Start or restart HA

### Debug logs

```text
2024-12-05 10:54:13.589 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'beward': Requirements for beward not found: ['ha-av>=9.2'].
```

**Comment by AlexObukhoff** [comment]
A similar problem

**Comment by booroondook-eng** [comment]
Tried to replace '>=9.2' with '>=10.0' but no effect.

**Comment by gshlomi** [comment]
+1

**Comment by nexustp** [comment]
+1

**Comment by eldoradik** [comment]
+1

**Comment by Vitaly-adm** [comment]
+1

**Comment by wayfarer70** [comment]
+1

**Comment by etairaz** [comment]
+1
Same problem

**Comment by and7ey** [comment]
@Limych could you please help with this?

**Comment by tjay4x4** [comment]
Такая же проблема, ошибка при установке Beward в HACS.

**Comment by Haronych** [comment]
+1

**Comment by diemon24** [comment]
+1


![image](https://github.com/user-attachments/assets/086eff47-4b6b-4527-8064-82e0f0c4f0a5)
Регистратор: beward.core
Источник: /usr/local/lib/python3.13/site-packages/beward/core.py:165
Первое сообщение: 01:15:09 (1 сообщений)
Последнее сообщение: 01:15:09

Error!
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
        conn,
    ...<5 lines>...
        chunked=chunked,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
    ~~~~~~~~~~~~~~^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.13/http/client.py", line 1428, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
                             " response")
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
        conn,
    ...<5 lines>...
        chunked=chunked,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
    ~~~~~~~~~~~~~~^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.13/http/client.py", line 1428, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
                             " response")
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/beward/core.py", line 161, in query
    req = self.session.get(url, params=params, auth=auth, timeout=TIMEOUT)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
