### ISSUE TITLE
Ошибки в логе НА

### ISSUE THREAD

**Issue by conrad66** [Limych/ha-beward#9]
Установлена последняя версия компонента 1.1.7
НА версии 0.115.2
после установке компонента вижу в логе следующее:
ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/components/ssdp/__init__.py", line 39, in initialize
await scanner.async_scan(None)
File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/components/ssdp/__init__.py", line 63, in async_scan
await self._process_entries(entries)
File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/components/ssdp/__init__.py", line 87, in _process_entries
result for result in await asyncio.gather(*tasks) if result is not None
File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/components/ssdp/__init__.py", line 127, in _process_entry
if all(info.get(k) == v for (k, v) in matcher.items()):
AttributeError: 'str' object has no attribute 'items'

После удаление компонента подобного не наблюдается.
В чем может быть причина ?

**Comment by Limych** [comment]
Во-первых, пожалуйста, оформляйте багрепорты в соответствии с предложенным шаблоном. Это последний раз, когда я реагирую на багрепорт не по шаблону. Все последующие будут закрываться без предупреждений и без желаемой Вами реакции.

Во-вторых, причина, скорее всего в настройках автодобавления устройства в систему. Эти настройки были добавлены, но не используются. В последней версии я их удалил.
